//! Raw FFI bindings for libghostty-vt, the Ghostty terminal engine's
//! parser and screen model, generated by rust-bindgen from its C headers
//! (`gen-bindings` regenerates `src/bindings.rs`). The `libghostty-vt` crate
//! wraps them in a safe API.
#![warn(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]

/// The generated bindings. Each item keeps the C header's name and meaning,
/// so the libghostty-vt headers are their documentation; the generator's
/// output is exempt from the crate's naming, lint and documentation rules.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    clippy::all,
    missing_docs,
    rustdoc::all
)]
mod bindings;

use std::ops::Deref;

pub use bindings::*;

/// Initialize a "sized" FFI object.
#[macro_export]
macro_rules! sized {
    ($ty:ty) => {{
        let mut t = <$ty as ::std::default::Default>::default();
        t.size = ::std::mem::size_of::<$ty>();
        t
    }};
}

impl<S> From<S> for bindings::String
where
    S: Deref<Target = str>,
{
    fn from(value: S) -> Self {
        Self {
            ptr: value.as_ptr(),
            len: value.len(),
        }
    }
}

impl bindings::String {
    /// Borrow the string as raw bytes. A null pointer is treated as an empty
    /// string; the C API does not promise a non-null pointer for zero-length
    /// strings, and `slice::from_raw_parts` requires one even at length zero.
    ///
    /// # Safety
    ///
    /// The caller must uphold that the associated lifetime is valid
    /// with the given context behind the FFI string.
    pub unsafe fn to_bytes<'a>(self) -> &'a [u8] {
        if self.ptr.is_null() {
            return &[];
        }
        // SAFETY: To be upheld by caller
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }

    /// Borrow the string as UTF-8 text, as [`Self::to_bytes`] does, without
    /// checking the encoding.
    ///
    /// # Safety
    ///
    /// The caller must uphold that the associated lifetime is valid
    /// with the given context behind the FFI string, and that it contains
    /// valid UTF-8 data.
    pub unsafe fn to_str<'a>(self) -> &'a str {
        // SAFETY: To be upheld by caller
        unsafe { std::str::from_utf8_unchecked(self.to_bytes()) }
    }
}

#[cfg(test)]
mod tests {
    use super::bindings;

    #[test]
    fn sized_macro_sets_the_size_field() {
        let colors = crate::sized!(bindings::RenderStateColors);
        assert_eq!(
            colors.size,
            std::mem::size_of::<bindings::RenderStateColors>()
        );
    }

    #[test]
    fn ffi_string_round_trips_static_str() {
        let raw = bindings::String::from("ghostty");
        assert_eq!(raw.len, "ghostty".len());
        // SAFETY: The source string is `'static` and valid UTF-8.
        assert_eq!(unsafe { raw.to_str() }, "ghostty");
    }

    #[test]
    fn ffi_string_round_trips_borrowed_string() {
        let owned = String::from("terminal");
        let raw = bindings::String::from(owned.as_str());
        // SAFETY: `owned` outlives the conversion and contains valid UTF-8.
        assert_eq!(unsafe { raw.to_str() }, "terminal");
    }
}
