use crate::error::Result;

use crate::component::Element;
use crate::core::renderer::Renderer;
use crate::core::surface::Rgba;
// use crate::core::render_ops::{RenderOps, RenderOpsBuilder};
use crate::core::grapheme_cell::GraphemeSurface;
use crate::core::span_diff::SpanDiffWriter;
use crate::event::types as rt_event;
use crate::render::reconcile::PatchOp;
use crate::render::tree::{RenderNode, RenderTree};

pub mod direct_tty;

/// Minimal, patch-driven backend abstraction
pub trait Backend: Send + Sync {
    /// Apply patch operations generated by the reconciler
    fn apply_patches(&mut self, patches: &[PatchOp], tree: &RenderTree) -> Result<()>;
    /// Clear the back buffer
    fn clear(&mut self) -> Result<()>;
    /// Present current frame
    fn present(&mut self) -> Result<()>;
    /// Return (cols, rows) if available
    fn size(&self) -> (u16, u16);
    /// Poll next high-level Event (converted from crossterm), with optional timeout in ms
    fn poll_event(&mut self, timeout_ms: Option<u64>) -> Result<Option<rt_event::Event>>;
    /// Enable/disable debug overlay if supported (default: no-op)
    fn set_debug_overlay(&mut self, _enabled: bool) {}
    /// Optional full render path (fallback)
    fn render_full(&mut self, _element: &Element) -> Result<()> {
        Ok(())
    }
}

/// Simple painter that writes text nodes from a RenderNode tree linearly (temporary scaffolding)
pub fn paint_render_node_linear(
    surface: &mut crate::core::surface::Surface,
    node: &dyn RenderNode,
    x: usize,
    y: usize,
) -> usize {
    use crate::component::ElementType;
    use crate::core::surface::{Attr, Rgba};
    let mut cur_y = y;
    if let Some(el) = node.as_element() {
        if let ElementType::Text(s) = &el.element_type {
            let fg = Rgba {
                r: 1.0,
                g: 1.0,
                b: 1.0,
                a: 1.0,
            };
            let bg = Rgba {
                r: 0.0,
                g: 0.0,
                b: 0.0,
                a: 1.0,
            };
            for (i, line) in s.lines().enumerate() {
                surface.write_str(x, cur_y + i, line, fg, bg, Attr::empty());
            }
            cur_y += s.lines().count().max(1);
        }
    }
    for child in node.children() {
        cur_y = paint_render_node_linear(surface, child.as_ref(), x, cur_y);
    }
    cur_y
}

/// Crossterm-backed implementation using our double-buffered Renderer
pub struct CrosstermBackend {
    renderer: Renderer,
    /// Use grapheme-aware surface for proper Unicode support
    grapheme_surface: GraphemeSurface,
    /// Previous frame for diffing
    prev_surface: Option<GraphemeSurface>,
    /// Use RenderOps pipeline when enabled
    use_render_ops: bool,
}

impl CrosstermBackend {
    pub fn new() -> Result<Self> {
        // Determine terminal size and initialize renderer buffers
        let (cols, rows) = crossterm::terminal::size().unwrap_or((80, 24));
        // Map cells to pixel-like surface width/height; for now treat as cells
        let renderer = Renderer::new(cols as usize, rows as usize)
            .map_err(|e| std::io::Error::other(e.to_string()))?;
        let grapheme_surface = GraphemeSurface::new(cols as usize, rows as usize);
        Ok(Self {
            renderer,
            grapheme_surface,
            prev_surface: None,
            use_render_ops: true, // Enable by default
        })
    }

    /// Enable or disable RenderOps pipeline
    pub fn set_use_render_ops(&mut self, enabled: bool) {
        self.use_render_ops = enabled;
    }

    /// Present using the RenderOps pipeline with grapheme-aware diffing
    fn present_with_render_ops(&mut self) -> Result<()> {
        use std::io::Write;

        // Copy from old Surface to GraphemeSurface
        let (width, height) = self.renderer.dims();
        let surface = self.renderer.surface_mut();

        // Transfer content to grapheme surface
        self.grapheme_surface.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });
        for y in 0..height {
            for x in 0..width {
                let cell = surface.get(x, y);
                use crate::core::grapheme_cell::CellType;
                use crate::core::grapheme_cell::GraphemeCluster;

                // Convert char to grapheme cluster
                let mut buf = [0u8; 4];
                let s = cell.ch.encode_utf8(&mut buf);
                let cluster = GraphemeCluster::new(s);

                self.grapheme_surface.set_cell(
                    x,
                    y,
                    CellType::Glyph {
                        grapheme: cluster,
                        fg: cell.fg,
                        bg: cell.bg,
                        attr: cell.attr,
                    },
                );
            }
        }

        // Generate diff if we have a previous frame
        let mut diff_writer = SpanDiffWriter::new();
        if let Some(ref prev) = self.prev_surface {
            diff_writer.diff(prev, &self.grapheme_surface);
        } else {
            // First frame - render everything
            let empty = GraphemeSurface::new(width, height);
            diff_writer.diff(&empty, &self.grapheme_surface);
        }

        // Output to terminal with synchronized updates
        let stdout = std::io::stdout();
        let mut stdout = stdout.lock();

        // Begin synchronized update
        stdout.write_all(b"\x1b[?2026h")?;
        stdout.write_all(b"\x1b[?25l")?; // Hide cursor

        // Write the diff
        stdout.write_all(diff_writer.output())?;

        // Show cursor and end synchronized update
        stdout.write_all(b"\x1b[?25h")?;
        stdout.write_all(b"\x1b[?2026l")?;
        stdout.flush()?;

        // Save current surface for next frame
        self.prev_surface = Some(self.grapheme_surface.clone());

        Ok(())
    }

    /// Apply patches selectively to minimize repainting
    fn apply_patches_selective(&mut self, patches: &[PatchOp], tree: &RenderTree) -> Result<()> {
        for patch in patches {
            match patch {
                PatchOp::Insert {
                    parent_key: _,
                    index: _,
                    node_key,
                } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: INSERT {node_key:?}");

                    // For inserts, we need to find the node and render it
                    if let Some(node) = tree.find_node(node_key) {
                        self.render_node_at_position(node, 0, 0)?;
                    }
                }

                PatchOp::Remove { node_key: _ } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: REMOVE");

                    // For removes, we need to clear the area where the node was
                    // For now, fall back to full repaint since we don't track positions
                    self.renderer.clear(Rgba {
                        r: 0.0,
                        g: 0.0,
                        b: 0.0,
                        a: 1.0,
                    });
                    if let Some(root) = tree.root() {
                        let surface = self.renderer.surface_mut();
                        let _end_y = paint_render_node_linear(surface, root, 0, 0);
                    }
                    return Ok(());
                }

                PatchOp::Update { node_key } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: UPDATE {node_key:?}");

                    // For updates, re-render the specific node
                    if let Some(node) = tree.find_node(node_key) {
                        self.render_node_at_position(node, 0, 0)?;
                    }
                }

                PatchOp::Replace {
                    old_key: _,
                    new_key: _,
                } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: REPLACE");

                    // For replaces, fall back to full repaint for now
                    self.renderer.clear(Rgba {
                        r: 0.0,
                        g: 0.0,
                        b: 0.0,
                        a: 1.0,
                    });
                    if let Some(root) = tree.root() {
                        let surface = self.renderer.surface_mut();
                        let _end_y = paint_render_node_linear(surface, root, 0, 0);
                    }
                    return Ok(());
                }

                PatchOp::Move {
                    node_key: _,
                    parent_key: _,
                    index: _,
                } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: MOVE");

                    // For moves, fall back to full repaint for now
                    self.renderer.clear(Rgba {
                        r: 0.0,
                        g: 0.0,
                        b: 0.0,
                        a: 1.0,
                    });
                    if let Some(root) = tree.root() {
                        let surface = self.renderer.surface_mut();
                        let _end_y = paint_render_node_linear(surface, root, 0, 0);
                    }
                    return Ok(());
                }

                PatchOp::ReorderChildren {
                    parent_key: _,
                    new_order: _,
                } => {
                    #[cfg(feature = "debug_patches")]
                    eprintln!("CrosstermBackend: REORDER_CHILDREN");

                    // For reorders, fall back to full repaint for now
                    self.renderer.clear(Rgba {
                        r: 0.0,
                        g: 0.0,
                        b: 0.0,
                        a: 1.0,
                    });
                    if let Some(root) = tree.root() {
                        let surface = self.renderer.surface_mut();
                        let _end_y = paint_render_node_linear(surface, root, 0, 0);
                    }
                    return Ok(());
                }
            }
        }
        Ok(())
    }

    /// Render a specific node at a given position
    fn render_node_at_position(&mut self, node: &dyn RenderNode, x: usize, y: usize) -> Result<()> {
        let surface = self.renderer.surface_mut();
        let _end_y = paint_render_node_linear(surface, node, x, y);
        Ok(())
    }

    fn map_ct_key_code(code: crossterm::event::KeyCode) -> rt_event::KeyCode {
        use crossterm::event::KeyCode as C;
        use rt_event::KeyCode as R;
        match code {
            C::Backspace => R::Backspace,
            C::Enter => R::Enter,
            C::Left => R::Left,
            C::Right => R::Right,
            C::Up => R::Up,
            C::Down => R::Down,
            C::Home => R::Home,
            C::End => R::End,
            C::PageUp => R::PageUp,
            C::PageDown => R::PageDown,
            C::Tab => R::Tab,
            C::BackTab => R::BackTab,
            C::Delete => R::Delete,
            C::Insert => R::Insert,
            C::Esc => R::Escape,
            C::Char(c) => R::Char(c),
            C::F(n) => R::F(n),
            _ => R::Unknown,
        }
    }

    fn map_ct_key_mods(m: crossterm::event::KeyModifiers) -> rt_event::KeyModifiers {
        rt_event::KeyModifiers {
            shift: m.contains(crossterm::event::KeyModifiers::SHIFT),
            ctrl: m.contains(crossterm::event::KeyModifiers::CONTROL),
            alt: m.contains(crossterm::event::KeyModifiers::ALT),
            meta: m.contains(crossterm::event::KeyModifiers::SUPER),
        }
    }

    fn map_ct_key_kind(k: crossterm::event::KeyEventKind) -> rt_event::KeyEventKind {
        use crossterm::event::KeyEventKind as C;
        use rt_event::KeyEventKind as R;
        match k {
            C::Press => R::Press,
            C::Release => R::Release,
            C::Repeat => R::Repeat,
        }
    }

    fn map_ct_mouse_button(b: crossterm::event::MouseButton) -> rt_event::MouseButton {
        use crossterm::event::MouseButton as C;
        use rt_event::MouseButton as R;
        match b {
            C::Left => R::Left,
            C::Right => R::Right,
            C::Middle => R::Middle,
        }
    }

    fn map_ct_event(e: crossterm::event::Event) -> Option<rt_event::Event> {
        use crossterm::event::Event as CE;
        match e {
            CE::Key(ke) => {
                let mut ev = rt_event::KeyEvent::new(Self::map_ct_key_code(ke.code))
                    .with_modifiers(Self::map_ct_key_mods(ke.modifiers))
                    .with_kind(Self::map_ct_key_kind(ke.kind));
                ev.repeat = ke.kind == crossterm::event::KeyEventKind::Repeat;
                Some(rt_event::Event::Key(ev))
            }
            CE::Resize(w, h) => Some(rt_event::Event::Resize(rt_event::ResizeEvent::new(w, h))),
            CE::Paste(text) => Some(rt_event::Event::Paste(rt_event::PasteEvent::new(text))),
            CE::FocusGained => Some(rt_event::Event::Focus(rt_event::FocusEvent {
                kind: rt_event::FocusEventKind::Gained,
                timestamp: std::time::Instant::now(),
            })),
            CE::FocusLost => Some(rt_event::Event::Focus(rt_event::FocusEvent {
                kind: rt_event::FocusEventKind::Lost,
                timestamp: std::time::Instant::now(),
            })),
            CE::Mouse(me) => {
                use crossterm::event::MouseEventKind as MK;
                let (x, y) = (me.column, me.row);
                let pos = rt_event::Position::cell(x, y);
                let kind = match me.kind {
                    MK::Down(_) => rt_event::MouseEventKind::Down,
                    MK::Up(_) => rt_event::MouseEventKind::Up,
                    MK::Drag(_) => rt_event::MouseEventKind::Drag,
                    MK::Moved => rt_event::MouseEventKind::Move,
                    MK::ScrollDown | MK::ScrollUp | MK::ScrollLeft | MK::ScrollRight => {
                        rt_event::MouseEventKind::Wheel
                    }
                };
                let btn = match me.kind {
                    MK::Down(b) | MK::Up(b) | MK::Drag(b) => Self::map_ct_mouse_button(b),
                    _ => rt_event::MouseButton::None,
                };
                let modifiers = Self::map_ct_key_mods(me.modifiers);
                let ev = rt_event::MouseEvent::new(kind, pos)
                    .with_button(btn)
                    .with_modifiers(modifiers);
                Some(rt_event::Event::Mouse(ev))
            }
        }
    }
}

impl Backend for CrosstermBackend {
    fn apply_patches(&mut self, patches: &[PatchOp], tree: &RenderTree) -> Result<()> {
        // Apply patches into the back buffer only; terminal sync happens in present()

        if patches.is_empty() {
            // Nothing to update in the back buffer
            return Ok(());
        }

        // For now, we'll implement a hybrid approach:
        // - If we have many patches or complex operations, fall back to full repaint
        // - Otherwise, apply patches selectively
        let should_full_repaint = patches.len() > 10
            || patches
                .iter()
                .any(|p| matches!(p, PatchOp::Replace { .. } | PatchOp::ReorderChildren { .. }));

        if should_full_repaint {
            // Fall back to full repaint for complex changes
            self.renderer.clear(Rgba {
                r: 0.0,
                g: 0.0,
                b: 0.0,
                a: 1.0,
            });
            if let Some(root) = tree.root() {
                let surface = self.renderer.surface_mut();
                let _end_y = paint_render_node_linear(surface, root, 0, 0);
            }
        } else {
            // Apply patches selectively
            self.apply_patches_selective(patches, tree)?;
        }

        Ok(())
    }

    fn clear(&mut self) -> Result<()> {
        self.renderer.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });
        Ok(())
    }

    fn present(&mut self) -> Result<()> {
        if self.use_render_ops {
            // Use the new RenderOps pipeline
            self.present_with_render_ops()
        } else {
            // Use the original renderer
            self.renderer
                .begin_frame()
                .map_err(|e| std::io::Error::other(e.to_string()))?;
            Ok(self
                .renderer
                .end_frame()
                .map_err(|e| std::io::Error::other(e.to_string()))?)
        }
    }

    fn set_debug_overlay(&mut self, enabled: bool) {
        self.renderer.set_debug_overlay(enabled);
    }

    fn size(&self) -> (u16, u16) {
        crossterm::terminal::size().unwrap_or((80, 24))
    }

    fn poll_event(&mut self, timeout_ms: Option<u64>) -> Result<Option<rt_event::Event>> {
        let ev = crate::core::terminal::Terminal::poll_event(timeout_ms)?;
        Ok(ev.and_then(Self::map_ct_event))
    }
}

/// Debug backend for testing reactive components with virtual screen buffer
pub struct DebugBackend {
    /// Virtual screen buffer for deterministic testing
    virtual_screen: crate::core::surface::Surface,
    /// Size of the virtual screen
    size: (u16, u16),
    /// Event queue for scripted testing
    event_queue: std::collections::VecDeque<rt_event::Event>,
    /// Patch history for debugging
    patch_history: Vec<Vec<PatchOp>>,
    /// Frame counter
    frame_count: usize,
}

impl DebugBackend {
    /// Create a new debug backend with specified dimensions
    pub fn new(width: u16, height: u16) -> Self {
        Self {
            virtual_screen: crate::core::surface::Surface::new(width as usize, height as usize),
            size: (width, height),
            event_queue: std::collections::VecDeque::new(),
            patch_history: Vec::new(),
            frame_count: 0,
        }
    }

    /// Add an event to the event queue for testing
    pub fn push_event(&mut self, event: rt_event::Event) {
        self.event_queue.push_back(event);
    }

    /// Get the current virtual screen content as a string for assertions
    pub fn screen_content(&self) -> String {
        let (w, h) = self.virtual_screen.dims();
        let mut content = String::new();
        for y in 0..h {
            for x in 0..w {
                let cell = self.virtual_screen.get(x, y);
                content.push(cell.ch);
            }
            if y < h - 1 {
                content.push('\n');
            }
        }
        content
    }

    /// Get a specific character at position (x, y)
    pub fn char_at(&self, x: usize, y: usize) -> Option<char> {
        let (w, h) = self.virtual_screen.dims();
        if x < w && y < h {
            Some(self.virtual_screen.get(x, y).ch)
        } else {
            None
        }
    }

    /// Find the position of a character on the screen
    pub fn find_char(&self, ch: char) -> Option<crate::core::geometry::Point> {
        let (w, h) = self.virtual_screen.dims();
        for y in 0..h {
            for x in 0..w {
                if self.virtual_screen.get(x, y).ch == ch {
                    return Some(crate::core::geometry::Point::new(x, y));
                }
            }
        }
        None
    }

    /// Get the patch history for debugging
    pub fn patch_history(&self) -> &[Vec<PatchOp>] {
        &self.patch_history
    }

    /// Get the current frame count
    pub fn frame_count(&self) -> usize {
        self.frame_count
    }

    /// Clear the virtual screen
    pub fn clear_screen(&mut self) {
        self.virtual_screen.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });
    }
}

impl Backend for DebugBackend {
    fn apply_patches(&mut self, patches: &[PatchOp], tree: &RenderTree) -> Result<()> {
        // Store patches for debugging
        self.patch_history.push(patches.to_vec());

        // For debug backend, we always do a full repaint for simplicity and determinism
        self.virtual_screen.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });

        if let Some(root) = tree.root() {
            let _end_y = paint_render_node_linear(&mut self.virtual_screen, root, 0, 0);
        }

        #[cfg(feature = "debug_patches")]
        {
            eprintln!(
                "DebugBackend: Applied {} patches in frame {}",
                patches.len(),
                self.frame_count
            );
            for (i, patch) in patches.iter().enumerate() {
                eprintln!("  Patch {i}: {patch:?}");
            }
        }

        Ok(())
    }

    fn clear(&mut self) -> Result<()> {
        self.virtual_screen.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });
        Ok(())
    }

    fn present(&mut self) -> Result<()> {
        self.frame_count += 1;

        #[cfg(feature = "debug_patches")]
        eprintln!("DebugBackend: Presented frame {}", self.frame_count);

        Ok(())
    }

    fn size(&self) -> (u16, u16) {
        self.size
    }

    fn poll_event(&mut self, _timeout_ms: Option<u64>) -> Result<Option<rt_event::Event>> {
        Ok(self.event_queue.pop_front())
    }

    fn render_full(&mut self, element: &Element) -> Result<()> {
        // For debug backend, convert element to render tree and paint
        use crate::render::tree::{element_to_render_node, RenderTree};

        let mut tree = RenderTree::new();
        let root = element_to_render_node(element.clone());
        tree.set_root(root);

        self.virtual_screen.clear(Rgba {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        });

        if let Some(root) = tree.root() {
            #[cfg(test)]
            #[allow(dead_code)]
            mod tests {
                use super::*;
                use crossterm::event::Event as CtEvent;

                #[test]
                fn map_paste_event() {
                    let ct = CtEvent::Paste("hello".to_string());
                    let mapped = CrosstermBackend::map_ct_event(ct).expect("mapped");
                    match mapped {
                        rt_event::Event::Paste(pe) => assert_eq!(pe.content, "hello"),
                        _ => panic!("expected Paste event"),
                    }
                }

                #[test]
                fn map_focus_gained_lost() {
                    let gained =
                        CrosstermBackend::map_ct_event(CtEvent::FocusGained).expect("mapped");
                    match gained {
                        rt_event::Event::Focus(f) => {
                            assert!(matches!(f.kind, rt_event::FocusEventKind::Gained))
                        }
                        _ => panic!("expected Focus(Gained)"),
                    }
                    let lost = CrosstermBackend::map_ct_event(CtEvent::FocusLost).expect("mapped");
                    match lost {
                        rt_event::Event::Focus(f) => {
                            assert!(matches!(f.kind, rt_event::FocusEventKind::Lost))
                        }
                        _ => panic!("expected Focus(Lost)"),
                    }
                }

                #[test]
                fn map_resize_event() {
                    let mapped =
                        CrosstermBackend::map_ct_event(CtEvent::Resize(100, 40)).expect("mapped");
                    match mapped {
                        rt_event::Event::Resize(r) => {
                            assert_eq!(r.width, 100);
                            assert_eq!(r.height, 40);
                        }
                        _ => panic!("expected Resize"),
                    }
                }

                #[test]
                fn map_key_event_basic() {
                    use crossterm::event::KeyEventState as Kes;
                    use crossterm::event::{
                        KeyCode as Kc, KeyEvent, KeyEventKind, KeyModifiers as Km,
                    };
                    let ct = CtEvent::Key(KeyEvent {
                        code: Kc::Char('a'),
                        modifiers: Km::CONTROL,
                        kind: KeyEventKind::Press,
                        state: Kes::NONE,
                    });
                    let mapped = CrosstermBackend::map_ct_event(ct).expect("mapped");
                    match mapped {
                        rt_event::Event::Key(k) => {
                            assert!(matches!(k.code, rt_event::KeyCode::Char('a')));
                            assert!(k.modifiers.ctrl);
                            assert!(matches!(k.kind, rt_event::KeyEventKind::Press));
                        }
                        _ => panic!("expected Key"),
                    }
                }

                #[test]
                fn map_mouse_event_basic() {
                    use crossterm::event::KeyModifiers as Km;
                    use crossterm::event::{MouseButton as Mb, MouseEvent, MouseEventKind as Mk};
                    let ct = CtEvent::Mouse(MouseEvent {
                        kind: Mk::Down(Mb::Left),
                        column: 10,
                        row: 5,
                        modifiers: Km::empty(),
                    });
                    let mapped = CrosstermBackend::map_ct_event(ct).expect("mapped");
                    match mapped {
                        rt_event::Event::Mouse(m) => {
                            assert!(matches!(m.kind, rt_event::MouseEventKind::Down));
                            assert_eq!(m.position, rt_event::Position::cell(10, 5));
                            assert!(matches!(m.button, rt_event::MouseButton::Left));
                        }
                        _ => panic!("expected Mouse"),
                    }
                }
            }

            let _end_y = paint_render_node_linear(&mut self.virtual_screen, root, 0, 0);
        }

        self.frame_count += 1;
        Ok(())
    }
}
