"""Serialize compiler declarations for the TypeScript native loader."""
import re


def typescript_names(schema):
    """Keep public declarations independent of consumers' resolveJsonModule flag."""
    return ('/** Generated by scripts/generate-native-header.py. */\n'
            'export type NativeFunctionName =\n'
            + '\n'.join('  | ' + repr(name) for name in schema['functions']) + ';\n')


def schema_from_ast(ast):
    nodes = [n for n in ast['inner'] if not n.get('loc', {}).get('includedFrom')]
    def spelling(value):
        return re.sub(r'\b(struct|union|enum) ', '', value).replace('_Bool', 'bool')
    schema = {'opaque': [], 'enums': [], 'records': {}, 'callbacks': {}, 'functions': {}}
    for node in nodes:
        name = node.get('name', '')
        kind = node.get('kind')
        if kind == 'RecordDecl' and name.startswith('RTui'):
            if not node.get('completeDefinition'):
                schema['opaque'].append(name)
            else:
                schema['records'][name] = {
                    'kind': node['tagUsed'],
                    'fields': {f['name']: spelling(f['type']['qualType'])
                               for f in node['inner'] if f['kind'] == 'FieldDecl'},
                }
        elif kind == 'EnumDecl' and name.startswith('RTui'):
            schema['enums'].append(name)
        elif kind == 'TypedefDecl' and '(*)(' in node.get('type', {}).get('qualType', ''):
            schema['callbacks'][name] = spelling(node['type']['qualType'])
        elif kind == 'FunctionDecl':
            schema['functions'][name] = {
                'result': spelling(node['type']['qualType'].split('(', 1)[0].strip()),
                'parameters': [spelling(p['type']['qualType']) for p in node.get('inner', [])
                               if p['kind'] == 'ParmVarDecl'],
            }
    return schema
