"""Tab roles, focus, selected-state speech and active panel editing."""
def exercise(root, keyboard, wait, named, state, click, speech, Atspi, speech_start):
    wait("Tabs control label absent", lambda: named(root, "Project sections"))
    tabs = wait("Tab list absent", lambda: named(root, "Tabs"))
    assert tabs.get_role() == Atspi.Role.PAGE_TAB_LIST, tabs.get_role_name()
    overview = wait("Overview tab absent", lambda: named(root, "Overview"))
    settings = wait("Settings tab absent", lambda: named(root, "Settings"))
    locked = named(root, "Unavailable")
    assert overview.get_role() == Atspi.Role.PAGE_TAB
    assert state(overview, Atspi.StateType.SELECTED)
    assert not state(locked, Atspi.StateType.ENABLED)
    start = speech_start()
    keyboard.key(0xff53)
    wait("Settings tab selection absent", lambda: state(settings, Atspi.StateType.SELECTED))
    wait("Settings tab focus absent", lambda: state(settings, Atspi.StateType.FOCUSED))
    wait("Orca did not announce Settings tab", lambda: speech("Settings", start) and speech("tab", start))
    assert not state(overview, Atspi.StateType.SELECTED)
    entry = wait("Active settings panel absent", lambda: named(root, "Project setting"))
    start = speech_start()
    assert entry.get_component_iface().grab_focus()
    wait("Orca did not announce panel entry", lambda: speech("Project setting", start))
    wait("Orca did not read the entry value", lambda: speech("seed", start))
    assert Atspi.Text.get_text(entry, 0, -1) == "seed"
    keyboard.key(0xff57)
    keyboard.key(ord('x'))
    wait("Panel entry editing failed", lambda: Atspi.Text.get_text(entry, 0, -1) == "seedx")
    wait("Entry caret position absent", lambda: Atspi.Text.get_caret_offset(entry) == 5)
    keyboard.key(0xff51)
    wait("Entry caret movement absent", lambda: Atspi.Text.get_caret_offset(entry) == 4)
    start = speech_start()
    click(overview)
    wait("Assistive tab activation failed", lambda: state(overview, Atspi.StateType.SELECTED))
    wait("Orca did not announce Overview tab", lambda: speech("Overview", start))
    assert named(root, "Project setting") is None
    close = wait("Close tab action absent", lambda: named(root, "Close Settings tab"))
    assert close.get_role() == Atspi.Role.PUSH_BUTTON
    click(close)
    wait("Assistive close left the tab exposed", lambda: named(root, "Settings") is None)
    assert state(overview, Atspi.StateType.SELECTED)
    print("A11Y Tabs: roles, disabled skipping, selection speech and panel editing passed", flush=True)
