"""Dialog role, focus, validation and result delivery with the real reader."""


def exercise(root, keyboard, wait, named, state, click, speech, Atspi, speech_start):
    dialog = wait("Confirmation dialog absent", lambda: named(root, "Confirm project"))
    assert dialog.get_role() == Atspi.Role.DIALOG
    ok = named(root, "OK")
    keyboard.key(0xff53)
    wait("Confirmation default focus absent", lambda: state(ok, Atspi.StateType.FOCUSED))
    wait("Orca did not read confirmation title", lambda: speech("Confirm project"))
    blocked = named(root, "Unavailable action")
    assert not state(blocked, Atspi.StateType.ENABLED)
    assert blocked.get_action_iface() is None
    click(ok)
    wait("Confirmation did not close", lambda: named(root, "Confirm project") is None)
    wait("Confirmation result missing", lambda: named(root, "Confirmation complete"))
    print("A11Y ConfirmationDialog: dialog speech, default focus, disabled action and completion passed", flush=True)
    keyboard.key(0xffc9)
    entry = wait("Input dialog entry absent", lambda: named(root, "Project name entry"))
    assert entry.get_role() == Atspi.Role.ENTRY
    wait("Input dialog autofocus absent", lambda: state(entry, Atspi.StateType.FOCUSED))
    wait("Orca did not read input label", lambda: speech("Project name entry"))
    start = speech_start()
    click(named(root, "OK"))
    error = wait("Required validation absent", lambda: named(root, "This field is required"))
    # An ARIA-style alert maps to a notification; Alert is for alert dialogs.
    assert error.get_role() == Atspi.Role.NOTIFICATION, error.get_role_name()
    wait("Orca did not announce validation", lambda: speech("This field is required", start))
    assert entry.get_component_iface().grab_focus()
    wait("Input refocus absent", lambda: state(entry, Atspi.StateType.FOCUSED))
    start = speech_start()
    for char in "demo":
        keyboard.key(ord(char))
    wait("Dialog text edit absent", lambda: Atspi.Text.get_text(entry, 0, -1) == "demo")
    warning = wait("Input warning absent", lambda: named(root, "Check spelling"))
    assert warning.get_role() == Atspi.Role.STATUS_BAR, warning.get_role_name()
    wait("Orca did not announce input warning", lambda: speech("Check spelling", start))
    click(named(root, "OK"))
    wait("Input dialog did not close", lambda: named(root, "Name project") is None)
    wait("Input result missing", lambda: named(root, "Confirmation complete; Input complete: demo"))
    print("A11Y InputDialog: entry speech, required error announcement, editing and confirmed result passed", flush=True)
    keyboard.key(0xffc9)
    entry = wait("Autocomplete entry absent", lambda: named(root, "Search projects", Atspi.Role.ENTRY))
    wait("Autocomplete focus absent", lambda: state(entry, Atspi.StateType.FOCUSED))
    wait("Orca did not read autocomplete input", lambda: speech("Search projects"))
    assert named(root, "Suggestions").get_role() == Atspi.Role.LIST_BOX
    alpine = named(root, "Alpine", Atspi.Role.LIST_ITEM)
    assert alpine is not None, "Autocomplete option absent"
    start = speech_start()
    keyboard.key(0xff54)
    wait("Autocomplete keyboard selection absent", lambda: state(alpine, Atspi.StateType.SELECTED))
    wait("Orca did not announce autocomplete selection", lambda: speech("Alpine", start))
    click(alpine)
    wait("Autocomplete did not close", lambda: named(root, "Choose project") is None)
    wait("Autocomplete result missing", lambda: named(root, "Confirmation complete; Input complete: demo; Autocomplete complete: Alpine"))
    print("A11Y AutocompleteDialog: input/list/option roles, selected speech, assistive selection and result passed", flush=True)
    keyboard.key(0xffc9)
    dialog = wait("Progress dialog absent", lambda: named(root, "Building project"))
    assert dialog.get_role() == Atspi.Role.DIALOG
    cancel = named(root, "Cancel")
    wait("Progress Cancel focus absent", lambda: state(cancel, Atspi.StateType.FOCUSED))
    bar = named(root, "Progress", Atspi.Role.PROGRESS_BAR)
    assert bar.get_value_iface().get_current_value() == .25
    start = speech_start()
    keyboard.reader_next_object(previous=True)
    wait("Orca did not read dialog progress", lambda: speech("25 percent", start))
    click(cancel)
    wait("Progress cancellation did not close", lambda: named(root, "Building project") is None)
    print("A11Y ProgressDialog: dialog/progress roles, numeric value speech and cancellation passed", flush=True)
    keyboard.key(0xffc9)
    wait("Wizard absent", lambda: named(root, "Project setup"))
    start = speech_start()
    click(named(root, "Next"))
    wait("Wizard validation absent", lambda: named(root, "Missing project details"))
    wait("Orca did not announce wizard validation", lambda: speech("Missing project details", start))
    click(named(root, "Skip"))
    entry = wait("Wizard next step absent", lambda: named(root, "Review notes"))
    start = speech_start()
    assert entry.get_component_iface().grab_focus()
    wait("Wizard input focus absent", lambda: state(entry, Atspi.StateType.FOCUSED))
    wait("Orca did not read wizard input", lambda: speech("Review notes", start) and speech("ready", start))
    keyboard.key(0xff57)
    keyboard.key(ord('x'))
    wait("Wizard editing failed", lambda: Atspi.Text.get_text(entry, 0, -1) == "readyx")
    click(named(root, "Finish"))
    wait("Wizard did not close", lambda: named(root, "Project setup") is None)
    print("A11Y WizardDialog: validation speech, step navigation, nested editing and completion passed", flush=True)
    start = speech_start()
    keyboard.key(0xffc9)
    background = wait("Toast background absent", lambda: named(root, "Background draft"))
    wait("Toast took background focus", lambda: state(background, Atspi.StateType.FOCUSED))
    wait("Toast message absent", lambda: named(root, "Project saved"))
    wait("Orca did not announce toast", lambda: speech("Project saved", start))
    wait("Toast did not expire", lambda: named(root, "Project saved") is None)
    assert state(background, Atspi.StateType.FOCUSED)
    print("A11Y Toast: message speech, expiry and retained background focus passed", flush=True)
    keyboard.key(0xffc9)
    dialog = wait("Generic dialog absent", lambda: named(root, "Generic details"))
    assert dialog.get_role() == Atspi.Role.DIALOG
    entry = named(root, "Generic notes")
    wait("Generic dialog focus absent", lambda: state(entry, Atspi.StateType.FOCUSED))
    wait("Orca did not read generic input", lambda: speech("Generic notes") and speech("draft"))
    keyboard.key(0xff57)
    keyboard.key(ord('x'))
    wait("Generic dialog editing failed", lambda: Atspi.Text.get_text(entry, 0, -1) == "draftx")
    keyboard.key(0xff1b)
    wait("Generic dialog did not close", lambda: named(root, "Generic details") is None)
    print("A11Y DialogBuilder: dialog and entry roles, input speech/editing and dismissal passed", flush=True)
